exports.RootController = require('./root-controller')
exports.SongController = require('./song-controller')
exports.VerseController = require('./verse-controller')
exports.QuoteController = require('./quote-controller')
exports.ScraperController = require('./scraper-controller')
